name: "text_recognition"  # Название модели
backend: "onnxruntime"  # Используемый бэкенд — ONNX Runtime
max_batch_size: 0  # Размер батча: 0 означает поддержку динамического батча

# Определение входных данных для модели
input [
  {
    name: "input.1"  # Название входного тензора (соответствует названию в ONNX-модели)
    data_type: TYPE_FP32  # Тип данных — 32-битное число с плавающей точкой (float32)
    dims: [ 1, 1, 32, 100 ]  # Размерность входного тензора: [batch_size, channels, height, width]
    # В данном случае размерность фиксирована для одного канала (черно-белое изображение), высота 32 и ширина 100 пикселей
  }
]

# Определение выходных данных для модели
output [
  {
    name: "308"  # Название выходного тензора (соответствует названию в ONNX-модели)
    data_type: TYPE_FP32  # Тип данных — 32-битное число с плавающей точкой (float32)
    dims: [ 1, 26, 37 ]  # Размерность выходного тензора: [batch_size, sequence_length, class_count]
    # Предполагается, что выходное значение представляет собой последовательность длиной 26 и 37 возможных классов (символов)
  }
]
