# Указание бэкенда, который будет использоваться для обработки модели.
# В данном случае это vLLM, который оптимизирован для работы с языковыми моделями.
backend: "vllm"

# Группа экземпляров (instance group) модели.
# Модель будет выполняться в одном экземпляре (count: 1).
# Использование KIND_MODEL означает, что распределение устройства (CPU/GPU) определяется vLLM.
instance_group [
  {
    count: 1
    kind: KIND_MODEL  # Используется механизм vLLM для распределения устройства (CPU/GPU)
  }
]
